directory: ~/Music
log: ~/.local/log/beets.log
library: ~/.local/share/beets/library.db

import:
  move: yes
  write: yes

plugins:
  acousticbrainz
  badfiles
  chroma
  convert
  discogs
  duplicates
  edit
  embedart
  fetchart
  ftintitle
  importadded
  info
  lastgenre
  mbcollection
  mbsync
  missing
  play
  random
  scrub
  web
  ydl
  zero
# lyrics

chroma:
  auto: yes

discogs:
  user_token: ITyPQOtMooHylPbxWReOVleFXDSHWwzujXqxcFiO

web:
  cors: "*"

lastgenre:
  count: 3

lasfm:
  user: matlads

musicbrainz:
  user: matlads
  pass: mart99

ui:
  color: yes

convert:
  auto: false

zero:
  keep_fields: title artist album year track genre images genres


# play:
#  command: /Applications/VLC.app/Contents/MacOS/VLC --no-video

# To install all the dependencies of this config install the following packages:
# apt install python3-flask python3-flask-cors python3-pylast python3-acoustid python3-pip youtube-dl mp3val flac ffmpeg imagemagick python3-requests 
# pip3 install --user beets-ydl discogs_client
